version: '3.8'

services:
  frontend:
    build:
      context: ./Artisanal-Dinnerware
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=168.231.122.169
      - DB_USER=admin
      - DB_PASS=Jhanvi@123
      - DB_NAME=laneofceramic
      - DB_PORT=3306
      - DATABASE_URL=mysql://admin:Jhanvi@123@168.231.122.169:3306/laneofceramic
    restart: unless-stopped
