version: '3.8'

services:


  frontend:
    build:
      context: ./Artisanal-Dinnerware
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - backend
    restart: unless-stopped

  admin:
    build:
      context: ./Admin-Panel
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - default
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laneofceramic
      MYSQL_USER: admin
      MYSQL_PASSWORD: Jhanvi@123
      MYSQL_ROOT_PASSWORD: Jhanvi@123
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    depends_on:
      - db
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=Jhanvi@123
      - DB_NAME=laneofceramic
      - DB_PORT=3306
      - DATABASE_URL=mysql://admin:Jhanvi@123@db:3306/laneofceramic
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  default:
